### PR TITLE
Fix changes pending WG validation

### LINKED ISSUE #99: Clean old examples

### PR DESCRIPTION
**Pull request by costateixeira**
A necessary cleanup was done for publication but some changes were introduced that could be misleading. To avoid that risk, this should be removed asap

### CODE REVIEW

**Comment by bdc-ehealth** [comment]
@costateixeira @jmp-ehealth
Hi guys, which issue is this merge to master linked to? Is this change related to the changes on branch issue-99 and the cleanup described in #99 . Traceability is important.

**Comment by costateixeira** [comment]
Right, this can be traced to any issue, but I was not sure what was "clean up old examples" - same issue as "clean up". 
So I found it better to just rever the unapproved changes, so that any new changes (the obvious fixes and the WG-approved changes) can be added now.

**Comment by bdc-ehealth** [comment]
I do not understand the contents of this pull request. It needs more clarification. In order not to block the other requests, I will temporarily revert it, until there is more explanation about this merge.

**Comment by costateixeira** [comment]
I think this was merged already.
This was made to fix the "cleanup" changes that were not requested nor
approved.

Changes to main should have a link to an issue and issues should be
resolved with the WG.

**Pull request merged**
